# 2021.12.31 수업내용
## C++
### Template
1. 1차원적인 것까지만 공부(강사님도 깊게는 안 하심)

### 예외처리
1. 예외의 종류
    1) C 런타임 라이브러리가 던지는 예외
    2) 메모리 참조 오류
    3) CPU가 던지는 예외(0으로 분모 나눗셈)

### 예외 처리(try-catch)
1. 목적
    1) 정상적인 동작 파트와 예외 처리 파트를 나누자!! (예외 처리 분기를 추가하여 나누자!) 
    2) Stack Unwinding (예외가 처리되지 않으면 예외가 발생한 함수를 호출한 영역으로 예외 데이터가 전달된다.)
        * 단점: 중첩된 호출이 있다면 throw가 던져졌는지 때문에, catch(type expr)에 전달되는 expr을 어디서 throw가 던져졌는지에 대한 증거 자료로 전달한다. (개체 등)
        * 예외처리가 될 때까지 호출 스택을 따라 계속 전달된다.
2. 문법
    <pre><code>
    try             
    {
        if (cond1)
            throw var; -> var은 catch의 expr과 자료형이 같아야 한다. (만약 일치하는 catch type이 없을 시 예외 처리가 되지 않는다.)
    }
    catch(type expr)        // try-catch는 하나의 문법(try 다음에는 무조건 catch가 작성되어야 함)
    {
    }    
    </code></pre>
3. Stack Unwinding
    1) 특징
    <pre><code>
    test()
    {
        throw var;  // stack Unwinding
    }
    test2()
    {
        try
        {
            test()
        }
        catch (type expr)
        {
            // test()에서 던진 throw에 대한 예외처리
        }
    }
    </code></pre>
    * main에서까지 예외 처리가 되지 않으면 C 런타임이 main 진입 전 (1단계 main)에 전달된다. (따라서, main 문을 나간 후에 main 바깥에서도 처리된다.)
    2) 응용 1
    <pre><code>
    int StoI(char* ch) throw (int, short) ->  throw (type): type에 해당하는 throw를 던진다고 명시함. (함수 내에서 다른 type 예외 작성 시 컴파일 에러)
    {
        // 문자->숫자 변환
        if(cond1)
            throw var;                  // stack Unwinding 됨
        if(cond2)
            throw var;                  // stack Unwinding
    }
    test2()
    {
        char* num = "12";
        try
        {
            cout << test(num) << endl;  // 문제 발생 시 throw를 전달받음
        }
        catch (int expr)              
        {
            // StoI()에서 던진 int형 throw에 대한 예외처리
        }
        catch (short expr)               
        {
            // StoI()에서 던진 short형 throw에 대한 예외처리
        }
    }
    </code></pre>
    3) 응용 2
    <pre><code>
    class Exception // 예외에 대한 처리 혹은 로그
    {
        public:
        void print(){...}
    }
    int tset(char* ch) throw (int, short)
    {
        if(cond1)
            throw var;                  // stack Unwinding 됨
    }
    test2()
    {
        char* num = "12";
        try
        {
            cout << test(num) << endl;  // 문제 발생 시 throw를 전달받음
        }
        catch (Exception  expr)               
        {
            // StoI()에서 던진 throw에 대한 예외처리
            expr.print();
        }
    }
    </code></pre>
4. 함수(호은 라이브러리) 제작자 입장에서는 throw를 던지는 것이 편하지만, 사용자 입장에서는 throw에 대한 처리가 이루어져야 하기 때문에 귀찮고 어렵다.
    * 프라우드의 서버엔진에서는 throw를 많이 사용함
5. 실제로 Stack Unwinding을 사용하면 try 문에서 어디까지가 예외처릭가 되었는지 안되었는지에 대한 파악이 어렵다.
6. 예외 처리 사용에 대한 언급 유명 인물: 스캇 마이어, 존 로빈, 비야네 스트로스트롬
8. 사용 시 주의사항
    * 예외 발생시 부하를 걱정하는 것은 예외를 정상 처리 과정과 **혼돈**하는 증상!! (함수의 실패와 예외는 완전 다른 문제이기 때문이다.)
    * 예외 처리는 가벼운 마음으로 쓰는 것이 아닌 사용에 대하여 신중히 결정해야 하는 문제이다.

### malloc, new 예외처리
1. new는 실패 시 예외를 던진다.(Bad Alloc 예외를 던진다)
2. 처리하지 않음
    * malloc의 경우에는 nullptr 쓰기 액세스 위반이 일어나 죽고 new는 예외를 던져 main까지 전달되어 종료되기 때문이다.
3. Unhandled exception(최상위 예외처리) 필터 등록하여 오류 내용에 대한 메모리 덤프를 기록하고 깔끔하게 프로세스를 종료시킨다.
4. 결함이 생기면 오류에 대한 메모리 덤프던 로그던 증거를 남기고 프로그램을 바로 죽이는 방향으로 가야한다.
    
### main 단계
1. 1단계 메인: 런타임 라이브러리가 전역 객체, 전역 변수 등을 초기화하는 메인 문
2. 2단계 메인: 실제 프로그래머가 작성하는 메인 문
    
